export const SET_OWNED_COLLECTIBLES = 'SET_OWNED_COLLECTIBLES';
export const SET_CONTRACT_COLLECTIBLES = 'SET_CONTRACT_COLLECTIBLES';
export const SET_COLLECTIBLE_TRANSACTION = 'SET_COLLECTIBLE_TRANSACTION';
export const RESET_COLLECTIBLE_TRANSACTION = 'RESET_COLLECTIBLE_TRANSACTION';
