export const SET_COLLECTIBLES = 'SET_COLLECTIBLES';
export const ADD_COLLECTIBLES = 'ADD_COLLECTIBLES';
export const SET_COLLECTIBLE_PREVIEW_TRANSACTION = 'SET_COLLECTIBLE_PREVIEW_TRANSACTION';
export const RESET_COLLECTIBLE_PREVIEW_TRANSACTION = 'RESET_COLLECTIBLE_PREVIEW_TRANSACTION';
export const SET_COLLECTIBLE_PENDING_TRANSACTION = 'SET_COLLECTIBLE_PENDING_TRANSACTION';
export const RESET_COLLECTIBLE_PENDING_TRANSACTION = 'RESET_COLLECTIBLE_PENDING_TRANSACTION';
