export const AVAILABLE_FOR_BORROW = 'AVAILABLE_FOR_BORROW';
export const AVAILABLE_FOR_LENDING = 'AVAILABLE_FOR_LEND';
export const APPROVED_FOR_LENDING = 'APPROVED_FOR_LENDING';
export const APPROVED_FOR_BORROWING = 'APPROVED_FOR_BORROWING';
export const SET_FOR_LENDING = 'SET_FOR_LENDING';
