export const SET_COLLECTIBLES = 'SET_COLLECTIBLES';
export const ADD_COLLECTIBLES = 'ADD_COLLECTIBLES';
export const SET_COLLECTIBLE_TRANSACTION = 'SET_COLLECTIBLE_TRANSACTION';
export const RESET_COLLECTIBLE_TRANSACTION = 'RESET_COLLECTIBLE_TRANSACTION';
